### ISSUE TITLE
read abstract and methods from word docs

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#21]
instead of text, to preserve formatting

**Comment by clnsmth** [comment]
Great recommendation @mobb. Support for MS Word and Markdown will be rolled out with `EMLassemblyline 3.0.0`, which incorporates the revised `EML` library. This development is active at: https://github.com/clnsmth/EMLassemblyline

**Comment by twhiteaker** [comment]
Here comes a hair pulling out comment.

Currently [instructions.md](https://github.com/EDIorg/EMLassemblyline/blob/master/documentation/instructions.md) says you can read from Word, but that you have to remove non-unicode characters using [this web site](http://utils.paranoiaworks.org/diacriticsremover/).  By the way, the link should now be https://pteo.paranoiaworks.mobi/diacriticsremover/.  Anyways, that site has a button that removes non-ASCII characters, which leaves you with a much smaller set of characters than Unicode.  UTF-8, a Unicode encoding, is fine for XML, so I don't see a reason to restrict abstracts and methods to ASCII...unless there's some deficiency with PASTA in storing non-ASCII characters in abstracts and methods.  [This package at the Arctic Data Center](https://arcticdata.io/catalog/view/doi:10.18739/A2GH9B86Q) seems to work fine with the word Utqiaġvik.

However, just pasting text into the box (without pushing the button) on that Diacritics Remover site will remove things like subscripts, so that can be useful.

However, maybe you want to keep some special formatting, like italics, or section headings, or numbered lists.  So maybe we shouldn't paste at all.

However, `set_TextType` does a poor job reading some special formatting from Word.  In my testing, sometimes it includes subscripts in `<subscript>` elements, but sometimes it leaves them completely out. And if often starts new paragraphs when special formatting occurs.  That's a bug with `set_TextType`, but it's still something an assembly line user would need to consider and so should be in the documentation.

What I'm getting at is, the assembly line instructions should provide the right guidance on how to best use Word documents for abstracts and methods.  I don't know what that guidance is yet, as I don't fully know what `set_TextType` handles well and what it does not.  But I lean toward, "Keep your docs simple," i.e., pasting into notepad++ or a text box on a website (which likely uses UTF-8) and copying the result back into Word.  (If you paste into notepad++ and save as a text file, set_TextType may try to read it as markdown, which could mess things up if you've violated or don't fully understand markdown rules.)

**Comment by clnsmth** [comment]
Thanks for these comments and recommendations @twhiteaker. 

Support for MS Word and markdown files will be available once `EMLassemblyline` is refactored for the `EML` v2.0.0 R package.

As per your recommendations, I've dropped the diacritics remover from the [template editing instructions](https://ediorg.github.io/EMLassemblyline/articles/edit_metadata_templates.html). 

Do you have suggestions for identifying non-UTF-8 encoded characters using R? I'd like to incorporate into `EMLassemblyline` validation checks.

**Comment by twhiteaker** [comment]
> Do you have suggestions for identifying non-UTF-8 encoded characters using R?

Sorry but I'm quite the R noob!

**Comment by clnsmth** [comment]
Text type metadata (abstract, methods, additional_info) can be input as .txt, .docx, or .md files, as of `EMLassemblyline v2.6.0`.
