### ISSUE TITLE
EAL not looking at EML 2.2 list of units, evidently

### ISSUE THREAD

**Issue by vanderbi** [EDIorg/EMLassemblyline#72]
A workshop participant could not get EAL to run successfully with the unit milligramPerLiter in her attributes table, although this is the unit that shows up in https://sbclter.msi.ucsb.edu/external/InformationManagement/EDI/units/EML_units_preferred.html.  When she changed the unit to milligramsPerLiter, EAL ran fine.

**Comment by srearl** [comment]
That seems to be problem with that particular sbclter resource as `milligramsPerLiter` is the correct form in the EML schema: https://github.com/NCEAS/eml/blob/master/xsd/eml-unitTypeDefinitions.xsd#L354

**Comment by mobb** [comment]
The schema also allows this: 
```
     <xs:enumeration value="milligramPerLiter"/>
```
the reason that both are allowed is for backward compatibility. the list I posted at sbclter.msi is the list of units that are not deprecated. deprecated units are still allowed, but not preferred.

**Comment by srearl** [comment]
Ah, yeah, and just a few lines above line 354 no less. Sorry for adding confusion.

**Comment by mobb** [comment]
no problem! keeps us on our toes! I still need to confirm that `milligramPerLiter` is indeed NOT in 2.1

**Comment by clnsmth** [comment]
EAL is validating the units against:
[eml-unitDictionary.xml (EML 2.1.0)](https://github.com/ropensci/emld/blob/b04be9456533852ad4ebedf62a02364e388d2e9d/inst/tests/eml-2.1.1/eml-unitDictionary.xml)
[eml-unitDictionary.xml (EML 2.2.0)](https://github.com/ropensci/emld/blob/a15b47778cd9b4478826e613eda33ee8f5811e3d/inst/tests/eml-2.2.0/eml-unitDictionary.xml)

milligramPerLiter is absent from both lists.

Since EAL is dependent on the `EML` and `emld` R packages I suggest EAL users stick with the list of units output from `EMLassemblyline::view_unit_dictionary()` or define them as custom.

**Comment by mobb** [comment]
I will check into that. milligramPerLiter is valid.

Second: recommend that EAL do two things (assuming it creates EML 2.2 by default):
1. drop validation against EML 2.1.x list
2. from EML 2.2 list, only suggest units that are NOT designated `deprecatedInFavorOf`. 
the list will be much smaller, and much less confusing.

**Comment by mobb** [comment]
Yes, the R EML package has an out-of-date unitDictionary. There is already an issue logged for it.

**Comment by clnsmth** [comment]
This issue will be resolved in the `emld` dependency (see https://github.com/ropensci/emld/issues/56).
